### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by rveitch** [rveitch/sift#1]
## To Do:

- [ ] Create an "Article" View #2 
  - [ ] Figure out how to implement "back" links in article view #3
- [ ] Create a geo "map" view  #4
